### PR TITLE
now one can add entries to a combo widget in the settings with a dict under the hood

### PR DESCRIPTION
**Pull request by seb5g**
first specify a str entry to be added in the list then an integer value to be associated with this key!

image

### CODE REVIEW

**Comment by seb5g** [comment]
related to #188 and PR #171

**Comment by seb5g** [comment]
@rgeneaux you're in charge for the review. When done and approved, I'll merge it!

**Comment by rgeneaux** [comment]
You're too fast :-) Haven't had time to try it out yet

**Comment by seb5g** [comment]
sorry I was doing a bit of branch cleaning...

**Comment by rgeneaux** [comment]
I was testing on a MockNamesAxes (lab computer is busy right now) and there is an issue when loading the preset

at /pymodaq/utils/parameter/utils.py:164 inside `def set_param_from_param(param_old, param_new):`

```
  elif isinstance(child_old.opts['limits'], dict):
      if child_new.value() not in child_old.opts['limits'].values():
          child_old.opts['limits'].update(dict(str(child_new.value()), child_new.value()))
```
the last line bugs:      dict should take a list of tuples. 
Also the new dictionary item to add to child_old.opts['limits']  should be something like {'Xaxis', 1}, not {str(1), 1}.

i'm unsure if other types of params use dictionary so I'll let you check it instead of breaking other stuff!

**Comment by seb5g** [comment]
I produced a battery of tests to make sure all kinds of Parameters can be encoded to xml and back
The method set_param_from_param is also fine

Could you check this using code from commit: https://github.com/PyMoDAQ/PyMoDAQ/commit/f0b6454865e04ec162bf30587926532f45176e79

**Comment by seb5g** [comment]
Actually this is the one:
https://github.com/PyMoDAQ/PyMoDAQ/commit/0ce46669ef6912e77761a60642ed1ce00a148ee0

**Comment by rgeneaux** [comment]
Ok so now (on pymodaq-dev branch + the changes to set_param_from_param), it works well to add a dict in the preset!
However, for some reason, the value that we added does not make it to the final daq_move. See test with one axis hard-coded in the plugin, the other added in the preset:
axes_test

What's strange is after initializing the daq_move and putting a debug point somewhere,
```
self.settings.child('multiaxes', 'axis').opts['limits']
Out[4]: {'DefinedInsidePlugin (value=1)': 1, 'DefinedInPreset (value=2)': 2}
```
the second value is there! No idea why it doesn't actually appear ?!

**Comment by seb5g** [comment]
that's because the Parameter doesn't notify the widget item that it's limits have changed. Settings the limits using `opts['limits']` will not notify. One should use the `child.setLimits(new_limits)` method. Do you want to try it?

**Pull request merged**
