### PR TITLE
Pull request for issue  #224

### PR DESCRIPTION
**Pull request by Ashwolaa**
From scan_factory.py
self.axes_indexes was built with the unique function in  get_info_from_positions and led to a sorting of the value.
This made it not reliable when doing backwards scan as the indexes given did not match the position array which was unsorted)

This fixes the issue #224 by keeping the iniital sorting given by the user

### CODE REVIEW

**Comment by seb5g** [comment]
image

**Comment by Ashwolaa** [comment]
Sorry, I am not sure to totally follow what approach you prefer and what tests are asked

The scanner gives:
**Before:**
position: initial definition from user (keep ordering)
axes_unique: unique + sorted version of position, the function get_nav_axes() outputs an Axis with this variable as data
axes_indexes: indexes relating the positions to the axes_unique array, these indexes are then used when storing data

**Within this pull request:**
position: initial definition from user (keep ordering) #_UNCHANGED_
axes_unique: unique + unsorted version of position, the function get_nav_axes() still outputs an Axis with this variable as data # _CHANGED: It is now unsorted in the same order as position_ 
axes_indexes: indexes relating the position to the axes_unique array, these indexes are then used when storing data # _CHANGED: This becomes a  "useless" variable when we do not repeat the same points as the indexes just follows the evolution of the position array so for a simple 2D scan [0,0 ; 0,1 ; 0,2 ; 1,0 ; 1,1 ; 1,2 ]_

In fact, I believe the best way to handle things is to not sort anything as the order in which the data are recorded can be of particular importance when having to deal with instabilities in an experiment. The user can then sort the data when he needs too and this option can be instead be added in the h5browser if needed

**Comment by seb5g** [comment]
Sorting may have its importance for proper plotting of the data... But I think the data were never sorted into the h5 file except for the 2D uniform grid cases (linear, back and forth and spiral) because then sorting them and placing them into a regular grid allows to plot the data as an image, otherwise if would be done using the triangulation method which for uniform grid data is ugly. 

So beware that because of the overall generality of PyMoDAq, what you think make sense could be more tricky than at first glance!

And indeed by testing your PR and trying to do a spiral scan, I got errors for the plotting. axes_indexes is the index in the sorted version of the axes (especially because of what I wrote above). 

Anyhow, I didn't get how it was supposed to create an error at the beginning of the issue #224 , could you expose more precisely how to reproduce the error you're seeing?

**Comment by Ashwolaa** [comment]
Minimal example with daq_scan + h5browser

- Launch daq_scan
- pick Det 2D
- pick XAxis as actuator
- With 1D Linear scan
Xaxis start: 50 / Xaxis stop: -50 / Xaxis step: -50
- Launch scan
- Open output file with h5browser
By scrolling at Data00, we can see that 50 is positionned at -50 and vice versa so indexes have been flipped somehow.

This example is to see it with the h5browser but this was first observed on experimental data directly

**Pull request closed without merging**
