### PR TITLE
Dashboard inherits CustomApp

### LINKED ISSUE #412: Improve splash screen when loading a preset
Make the text larger and perhaps enhance the screen, some random ideas:
- a loading bar that gets incremented each time of the module is correctly loaded?
- a list of modules to load with checkmarks that get added as they get loaded?

### PR DESCRIPTION
**Pull request by seb5g**
Implements the CustomApp behaviour.

In particular, this allow a better and cleaner use of QActions both for the menu and the toolbar
Introducing important QActions in the toolbar:

* select preset
* load it
* open DAQ_Scan
* open help
* open plugin manager

image

handle a better splashsreen:
image

### CODE REVIEW

**Comment by seb5g** [comment]
@rgeneaux could you have a look and maybe tell me what could be done on top of that?

**Comment by seb5g** [comment]
solve #412

**Comment by seb5g** [comment]
@rgeneaux could you install this branch and tell me if the user experience is better with the toolbar?
@quantumm idem
@aurore-finco idem

**Comment by rgeneaux** [comment]
Toolbar is great! noticed this tooltip 
image
I think it should simply say "General settings"

**Comment by seb5g** [comment]
good catch

**Pull request merged**
