### PR TITLE
added the callable csv file in a ugly table in Library reference

### PR DESCRIPTION
**Pull request by loicguilmard**
I can't seem to change the table td font size  so we have to use shift+wheel to see the right side of the table.
It's usable and handy but not beautiful.

Note on the csv generation :
The csv file is not dynamic (yet ?) since i need to load the callable tree in 2 different environements.
I referenced all the methods, functions loops in github.com/loicguilmard/modulexplorer but it doesn't work as is.
It need 2 env and 3 runs (and debug/polishing).

### CODE REVIEW

**Comment by seb5g** [comment]
well, once you will have generated the differences, it is no big deal if the table is static? If you really want to, I guess you could use a github action to do so...

Have you checked:

* https://pypi.org/project/sphinx-csv-tools/
* https://github.com/alterat/tables-with-sphinx

**Comment by loicguilmard** [comment]
yes i did.
the csv-tool is more about static filtering, but there is no material searchable table or something fancy like that.
the longtable doesn't break line with the point and i am not sure we want that.
the only solution i could apply was to change the font size in my brower :/
did you check the list ? 
1. It's really exaustive about the callable because it's hard to categorize what we are looking for (functions, methods, obejct type, etc...)
2. It also reference the callable that didn't move. I thought it could be interesting to actually find that a callable didn't move instead of "knowing by omission".

**Comment by loicguilmard** [comment]
Found a sphinx extension to make it responsive.
I had to force overflow in a custom css to handle long entries.
It's a ugly for those but it's much better that without the extension and the overflow.

**Comment by seb5g** [comment]
That's a huge list indeed! Could be a good reference with a ctrl+F you find where a class is now! I noticed you also included class that are imported. The red stuff below are imported things. They should not appear here. I mean on the left side of your table should appear the class that are defined (not imported) and on the right the new place where they are defined. This is important (I think) because I left some modules as they were before where I removed the class definition and imported them from their new location. This allows backcompatibility but should not be reference in your table.

image

**Comment by loicguilmard** [comment]
Then refuse this PR, my method was wrong. It was a module exploration to find callables. If you import it, it's a callable.

**Comment by seb5g** [comment]
the approach is still valid, you just have to check wether things are declared? I don't know how to do that but it should be doable

**Pull request closed without merging**
