### PR TITLE
Entrypoints

### PR DESCRIPTION
**Pull request by seb5g**

### CODE REVIEW

**Comment by rgeneaux** [comment]
Hi @seb5g ,
This broke things for me, running python 3.8 and pymodaq 4.0.4 : 

(v4) PS C:\Users\rgeneaux> dashboard
Traceback (most recent call last):
  File "C:\Miniconda3\envs\v4\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Miniconda3\envs\v4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\v4\Scripts\dashboard.exe\__main__.py", line 4, in <module>
  File "C:\Miniconda3\envs\v4\lib\site-packages\pymodaq\dashboard.py", line 54, in <module>
    extensions = extmod.get_extensions()
  File "C:\Miniconda3\envs\v4\lib\site-packages\pymodaq\extensions\utils.py", line 26, in get_extensions
    discovered_extension = metadata.entry_points()['pymodaq.extensions']
KeyError: 'pymodaq.extensions'

is python3.10 recommended now?
cheers

**Comment by seb5g** [comment]
For a long time this was the source of tests not passing when using py10 in the CI. I figured out that python had a regression bug on this and wrote that. However, I no more checked for the existence of the 'pymodaq.extensions' entry before getting the dictionnary value. So for old plugins where this entrypoint was not defined in the setup this creates an error.

I'll transform this immediately in metadata.entry_points().get('pymodaq.extensions', []) so that it returns an empty list and doesn't raise an error

Could you test this patch on the entry_point branch?

**Comment by seb5g** [comment]
and I'm beginning to use more py10 and py11 to see what's happening (especially on the things the tests don't cover yet)

**Comment by seb5g** [comment]
and the issue was also because the default instrument plugin package (the mock one) didn't have this defined entry_points either... I patched this

**Comment by seb5g** [comment]
I think I finally solved everything...
I also used this to make sure the CI applies to the current checked out branch

**Comment by seb5g** [comment]
True that's annoying...
I'll replace this with a debug level

**Pull request merged**
